### ISSUE TITLE
Customize Partitioning Scheme

### ISSUE THREAD

**Issue by gsingh93** [vitamins/archinstaller#22]
This script looks great, but the only thing that's missing for me is the ability to customize my partitioning scheme. Anyway you can add that in? Instead of having variables like `root_size` or `swap_size`, you could have an array of `partition_sizes` followed by an array of `fs_types`. Then you could loop through them and make all of them.

The only thing you'd need to watch out for would be making the fourth partition when using the MBR and extended partition.

**Comment by vitamins** [comment]
Hi,
thank you for your feedback. As a shortcut to customizing the partition scheme, you can set manual_part='yes' in ari.conf . That means you can use gparted or any partition editor you like to create the partitions before starting the script. This is described in the README.
About your suggestion to create an array of partition sizes and fstypes:
There are a lot of things to watch out for when implementing this. First partition size and fstype is not enough information, you would also need information about the partition type code. ( For example Linux filesystem has code 8300). Secondly there are hard requirements on partitions that need to be created, for example the root partition and the ESP for UEFI booting. That means additional checks are necessary that verify if ESP is present, BIOS boot partition is present and so on.
Secondly there are some type of partitions that do not contain a filesystem to be created with mkfs, for example the BIOS boot partition and swap partition. This requires additional logic to determine what to do after creating the partition.
Lastly, the automatic setup of partitions in this script was never meant to cover every possible case. It is designed to be usable for the majority of use cases. For all other cases one can fallback to manual partitioning.

All in all the comlexity of implementation is too high for a simple script like this. That said you can convince me otherwise by providing a patch or working example for this suggestion.
All the best
